In [2]:
clusterMapping = {
    "Techwear": {
        "Feminine": 0,
        "Romantic": 0,
        "Dreamy": 0,
        "Youthful": 0,
        "Punk": 0,
        "Alternative": 2,
        "Grunge": 1,
        "Streetwear": 2,
        "Quirky": 0,
        "Vintage-Inspired": 0,
        "Creative": 0,
        "Nostalgic": 0,
        "Playful": 0,
        "Glam": 0,
        "Minimalist": 0,
        "Classic": 0,
        "Polished": 0,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 0,
        "Timeless Elegance": 0,
        "Sporty": 0,
        "Functional": 3
    },
    "Athleisure": {
        "Feminine": 0,
        "Romantic": 0,
        "Dreamy": 0,
        "Youthful": 0,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 0,
        "Streetwear": 1,
        "Quirky": 0,
        "Vintage-Inspired": 0,
        "Creative": 0,
        "Nostalgic": 0,
        "Playful": 0,
        "Glam": 0,
        "Minimalist": 1,
        "Classic": 0,
        "Polished": 0,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 0,
        "Timeless Elegance": 0,
        "Sporty": 3,
        "Functional": 3
    },
    "Old Money": {
        "Feminine": 0,
        "Romantic": 0,
        "Dreamy": 0,
        "Youthful": 0,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 0,
        "Streetwear": 0,
        "Quirky": 0,
        "Vintage-Inspired": 0,
        "Creative": 0,
        "Nostalgic": 0,
        "Playful": 0,
        "Glam": 0,
        "Minimalist": 0,
        "Classic": 3,
        "Polished": 2,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 2,
        "Timeless Elegance": 3,
        "Sporty": 0,
        "Functional": 0
    },
    "Skater Hip-Hop": {
        "Feminine": 0,
        "Romantic": 0,
        "Dreamy": 0,
        "Youthful": 0,
        "Punk": 0,
        "Alternative": 2,
        "Grunge": 1,
        "Streetwear": 3,
        "Quirky": 0,
        "Vintage-Inspired": 0,
        "Creative": 0,
        "Nostalgic": 0,
        "Playful": 2,
        "Glam": 0,
        "Minimalist": 0,
        "Classic": 0,
        "Polished": 0,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 0,

        "Timeless Elegance": 0,
        "Sporty": 0,
        "Functional": 0
    },
    "Casual Corpo": {
        "Feminine": 0,
        "Romantic": 0,
        "Dreamy": 0,
        "Youthful": 0,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 0,
        "Streetwear": 0,
        "Quirky": 0,
        "Vintage-Inspired": 0,
        "Creative": 0,
        "Nostalgic": 0,
        "Playful": 0,
        "Glam": 0,
        "Minimalist": 2,
        "Classic": 2,
        "Polished": 1,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 0,
        "Timeless Elegance": 0,
        "Sporty": 0,
        "Functional": 0
    },
    "Soft Girl": {
        "Feminine": 3,
        "Romantic": 3,
        "Dreamy": 3,
        "Youthful": 2,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 0,
        "Streetwear": 2,
        "Quirky": 1,
        "Vintage-Inspired": 2,
        "Creative": 1,
        "Nostalgic": 2,
        "Playful": 2,
        "Glam": 1,
        "Minimalist": 1,
        "Classic": 0,
        "Polished": 0,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 0,

        "Timeless Elegance": 0,
        "Sporty": 0,
        "Functional": 1
    },
    "Indie/Artsy": {
        "Feminine": 1,
        "Romantic": 1,
        "Dreamy": 2,
        "Youthful": 2,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 1,
        "Streetwear": 0,
        "Quirky": 2,
        "Vintage-Inspired": 2,
        "Creative": 3,
        "Nostalgic": 0,
        "Playful": 2,
        "Glam": 0,
        "Minimalist": 0,
        "Classic": 0,
        "Polished": 0,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 0,
        "Timeless Elegance": 0,
        "Sporty": 1,
        "Functional": 1
    },
    "Y2K Revival": {
        "Feminine": 2,
        "Romantic": 1,
        "Dreamy": 1,
        "Youthful": 3,
        "Punk": 1,
        "Alternative": 0,
        "Grunge": 2,
        "Streetwear": 2,
        "Quirky": 0,
        "Vintage-Inspired": 1,
        "Creative": 3,
        "Nostalgic": 3,
        "Playful": 2,
        "Glam": 0,
        "Minimalist": 0,
        "Classic": 0,
        "Polished": 0,
        "Indo-Western": 0,
        "Fusion": 1,
        "Luxury Minimalism": 0,

        "Timeless Elegance": 2,
        "Sporty": 0,
        "Functional": 0
    },
    "Desi Modern": {
        "Feminine": 0,
        "Romantic": 3,
        "Dreamy": 1,
        "Youthful": 1,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 0,
        "Streetwear": 0,
        "Quirky": 0,
        "Vintage-Inspired": 1,
        "Creative": 1,
        "Nostalgic": 0,
        "Playful": 0,
        "Glam": 3,
        "Minimalist": 0,
        "Classic": 2,
        "Polished": 2,
        "Indo-Western": 3,
        "Fusion": 3,
        "Luxury Minimalism": 0,

        "Timeless Elegance": 1,
        "Sporty": 0,
        "Functional": 2
    },
    "Corporate Chic": {
        "Feminine": 1,
        "Romantic": 0,
        "Dreamy": 0,
        "Youthful": 2,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 0,
        "Streetwear": 0,
        "Quirky": 0,
        "Vintage-Inspired": 1,
        "Creative": 0,
        "Nostalgic": 0,
        "Playful": 0,
        "Glam": 0,
        "Minimalist": 2,
        "Classic": 2,
        "Polished": 3,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 3,
        "Timeless Elegance": 1,
        "Sporty": 0,
        "Functional": 2
    },
    "Quiet Luxury": {
        "Feminine": 0,
        "Romantic": 1,
        "Dreamy": 0,
        "Youthful": 0,
        "Punk": 0,
        "Alternative": 0,
        "Grunge": 0,
        "Streetwear": 0,
        "Quirky": 0,
        "Vintage-Inspired": 0,
        "Creative": 0,
        "Nostalgic": 0,
        "Playful": 0,
        "Glam": 1,
        "Minimalist": 3,
        "Classic": 3,
        "Polished": 3,
        "Indo-Western": 0,
        "Fusion": 0,
        "Luxury Minimalism": 2,
        "Timeless Elegance": 3,
        "Sporty": 0,
        "Functional": 2
    }
}

In [3]:
techwearVector       = list(clusterMapping["Techwear"].values())
AthleisureVector     = list(clusterMapping["Athleisure"].values())
Old_Moneyvector      = list(clusterMapping["Old Money"].values())
Skater_HHVector      = list(clusterMapping["Skater Hip-Hop"].values())
Casual_CorpoVector   = list(clusterMapping["Casual Corpo"].values())
Soft_GirlVector      = list(clusterMapping["Soft Girl"].values())
Indie_ArtsyVector    = list(clusterMapping["Indie/Artsy"].values())
Y2K_RevivalVector    = list(clusterMapping["Y2K Revival"].values())
Desi_ModernVector    = list(clusterMapping["Desi Modern"].values())
Corporate_ChicVector = list(clusterMapping["Corporate Chic"].values())
Quiet_LuxuryVector   = list(clusterMapping["Quiet Luxury"].values())


In [4]:
import numpy as np 

clusterMatrix = np.array([techwearVector, AthleisureVector,Old_Moneyvector,
                        Skater_HHVector,Casual_CorpoVector,Soft_GirlVector,
                        Indie_ArtsyVector,Y2K_RevivalVector,Desi_ModernVector,
                        Corporate_ChicVector,Quiet_LuxuryVector])



In [5]:
print(clusterMatrix)
print(clusterMatrix.shape)



[[0 0 0 0 0 2 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 3 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 2 0 0 2 3 0 0]
 [0 0 0 0 0 2 1 3 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 0 0 0 0 0 0]
 [3 3 3 2 0 0 0 2 1 2 1 2 2 1 1 0 0 0 0 0 0 0 1]
 [1 1 2 2 0 0 1 0 2 2 3 0 2 0 0 0 0 0 0 0 0 1 1]
 [2 1 1 3 1 0 2 2 0 1 3 3 2 0 0 0 0 0 1 0 2 0 0]
 [0 3 1 1 0 0 0 0 0 1 1 0 0 3 0 2 2 3 3 0 1 0 2]
 [1 0 0 2 0 0 0 0 0 1 0 0 0 0 2 2 3 0 0 3 1 0 2]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 1 3 3 3 0 0 2 3 0 2]]
(11, 23)


In [6]:

clusScores = {}

for clust,tags in clusterMapping.items():
  score = sum(tags.values())
  clusScores[clust] = score


In [7]:
print(clusScores.items())
print(clusScores)

dict_items([('Techwear', 8), ('Athleisure', 8), ('Old Money', 10), ('Skater Hip-Hop', 8), ('Casual Corpo', 5), ('Soft Girl', 24), ('Indie/Artsy', 18), ('Y2K Revival', 24), ('Desi Modern', 23), ('Corporate Chic', 17), ('Quiet Luxury', 18)])
{'Techwear': 8, 'Athleisure': 8, 'Old Money': 10, 'Skater Hip-Hop': 8, 'Casual Corpo': 5, 'Soft Girl': 24, 'Indie/Artsy': 18, 'Y2K Revival': 24, 'Desi Modern': 23, 'Corporate Chic': 17, 'Quiet Luxury': 18}


In [8]:

tagsvector =  [
    "Alternative", "Grunge", "Streetwear", "Minimalist", "Classic",
    "Polished", "Timeless Elegance", "Quirky", "Vintage-Inspired",
    "Feminine", "Romantic", "Dreamy", "Playful", "Creative",
    "Bohemian-lite", "Punk", "Indo-Western", "Fusion",
    "Luxury Minimalism",
]

In [9]:
colorvecrtor = ["Pastels","jewel-tones","Monochrome-Neutrals","Earth-tones","Muted-pastel","Bold-brights","Metallics","plaids-darkhues","blacks"]

In [10]:
clusterToColorMap = {
    "Techwear": {
        "Pastels": 0,
        "Jewel tones": 0,
        "Monochrome / Neutrals": 3,
        "Earth tones": 0,
        "Muted pastels": 0,
        "Bold brights": 0,
        "Metallics": 2,
        "Plaids / Dark hues": 1,
        "Blacks": 0
    },
    "Athleisure": {
        "Pastels": 0,
        "Jewel tones": 0,
        "Monochrome / Neutrals": 2,
        "Earth tones": 0,
        "Muted pastels": 0,
        "Bold brights": 2,
        "Metallics": 0,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    },
    "Old Money": {
        "Pastels": 0,
        "Jewel tones": 2,
        "Monochrome / Neutrals": 3,
        "Earth tones": 0,
        "Muted pastels": 0,
        "Bold brights": 0,
        "Metallics": 0,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    },
    "Skater Hip-Hop": {
        "Pastels": 0,
        "Jewel tones": 0,
        "Monochrome / Neutrals": 1,
        "Earth tones": 0,
        "Muted pastels": 0,
        "Bold brights": 2,
        "Metallics": 0,
        "Plaids / Dark hues": 2,
        "Blacks": 0
    },
    "Casual Corpo": {
        "Pastels": 0,
        "Jewel tones": 0,
        "Monochrome / Neutrals": 3,
        "Earth tones": 0,
        "Muted pastels": 0,
        "Bold brights": 0,
        "Metallics": 0,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    },
    "Soft Girl": {
        "Pastels": 3,
        "Jewel tones": 1,
        "Monochrome / Neutrals": 0,
        "Earth tones": 1,
        "Muted pastels": 2,
        "Bold brights": 0,
        "Metallics": 0,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    },
    "Indie/Artsy": {
        "Pastels": 1,
        "Jewel tones": 2,
        "Monochrome / Neutrals": 0,
        "Earth tones": 3,
        "Muted pastels": 1,
        "Bold brights": 3,
        "Metallics": 0,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    },
    "Y2K Revival": {
        "Pastels": 1,
        "Jewel tones": 1,
        "Monochrome / Neutrals": 0,
        "Earth tones": 0,
        "Muted pastels": 1,
        "Bold brights": 3,
        "Metallics": 2,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    },
    "Desi Modern": {
        "Pastels": 1,
        "Jewel tones": 3,
        "Monochrome / Neutrals": 0,
        "Earth tones": 2,
        "Muted pastels": 1,
        "Bold brights": 2,
        "Metallics": 2,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    },
    "Corporate Chic": {
        "Pastels": 0,
        "Jewel tones": 0,
        "Monochrome / Neutrals": 0,
        "Earth tones": 1,
        "Muted pastels": 0,
        "Bold brights": 0,
        "Metallics": 0,
        "Plaids / Dark hues": 1,
        "Blacks": 1
    },
    "Quiet Luxury": {
        "Pastels": 0,
        "Jewel tones": 1,
        "Monochrome / Neutrals": 3,
        "Earth tones": 3,
        "Muted pastels": 1,
        "Bold brights": 0,
        "Metallics": 0,
        "Plaids / Dark hues": 0,
        "Blacks": 0
    }
}


In [29]:
techwearVectorColor = list(clusterToColorMap["Techwear"].values())
AthleisureVectorColor = list(clusterToColorMap["Athleisure"].values())
Old_MoneyvectorColor = list(clusterToColorMap["Old Money"].values())
Skater_HHVectorColor = list(clusterToColorMap["Skater Hip-Hop"].values())
Casual_CorpoVectorColor = list(clusterToColorMap["Casual Corpo"].values())
Soft_GirlVectorColor = list(clusterToColorMap["Soft Girl"].values())
Indie_ArtsyVectorColor = list(clusterToColorMap["Indie/Artsy"].values())
Y2K_RevivalVectorColor = list(clusterToColorMap["Y2K Revival"].values())
Desi_ModernVectorColor = list(clusterToColorMap["Desi Modern"].values())
Corporate_ChicVectorColor = list(clusterToColorMap["Corporate Chic"].values())
Quiet_LuxuryVectorColor = list(clusterToColorMap["Quiet Luxury"].values())

colorMatrix = np.array([techwearVectorColor, AthleisureVectorColor, Old_MoneyvectorColor,
                        Skater_HHVectorColor, Casual_CorpoVectorColor, Soft_GirlVectorColor,
                        Indie_ArtsyVectorColor, Y2K_RevivalVectorColor, Desi_ModernVectorColor,
                        Corporate_ChicVectorColor, Quiet_LuxuryVectorColor])

print(colorMatrix)
print(colorMatrix.shape) 

[[0 0 3 0 0 0 2 1 0]
 [0 0 2 0 0 2 0 0 0]
 [0 2 3 0 0 0 0 0 0]
 [0 0 1 0 0 2 0 2 0]
 [0 0 3 0 0 0 0 0 0]
 [3 1 0 1 2 0 0 0 0]
 [1 2 0 3 1 3 0 0 0]
 [1 1 0 0 1 3 2 0 0]
 [1 3 0 2 1 2 2 0 0]
 [0 0 0 1 0 0 0 1 1]
 [0 1 3 3 1 0 0 0 0]]
(11, 9)


In [11]:
colorscores = {}

for clust,color in clusterToColorMap.items():
  scores = sum(color.values())
  colorscores[clust] = scores
print(colorscores)

{'Techwear': 6, 'Athleisure': 4, 'Old Money': 5, 'Skater Hip-Hop': 5, 'Casual Corpo': 3, 'Soft Girl': 7, 'Indie/Artsy': 10, 'Y2K Revival': 8, 'Desi Modern': 11, 'Corporate Chic': 3, 'Quiet Luxury': 8}


In [12]:
LifeStyleMapping = {
    "Techwear": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 0,
        "College Casual": 0,
        "Travel / Outdoor": 2,
        "Party & Clubbing": 0,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 0,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 0,
        "Cafe Hopping / Bookstore Runs": 0,
        "Gym & Fitness": 3
    },
    "Athleisure": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 0,
        "College Casual": 1,
        "Travel / Outdoor": 2,
        "Party & Clubbing": 0,
        "Chill at Home": 2,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 0,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 0,
        "Cafe Hopping / Bookstore Runs": 0,
        "Gym & Fitness": 3
    },
    "Old Money": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 3,
        "College Casual": 0,
        "Travel / Outdoor": 0,
        "Party & Clubbing": 0,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 1,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 2,
        "Cafe Hopping / Bookstore Runs": 0,
        "Gym & Fitness": 0
    },
    "Skater Hip-Hop": {
        "Music & Gig Nights": 2,
        "Corporate / Office": 0,
        "College Casual": 2,
        "Travel / Outdoor": 0,
        "Party & Clubbing": 2,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 0,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 0,
        "Cafe Hopping / Bookstore Runs": 0,
        "Gym & Fitness": 0
    },
    "Casual Corpo": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 3,
        "College Casual": 1,
        "Travel / Outdoor": 0,
        "Party & Clubbing": 0,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 0,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 0,
        "Cafe Hopping / Bookstore Runs": 1,
        "Gym & Fitness": 0
    },
    "Soft Girl": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 0,
        "College Casual": 2,
        "Travel / Outdoor": 1,
        "Party & Clubbing": 0,
        "Chill at Home": 1,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 0,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 2,
        "Cafe Hopping / Bookstore Runs": 3,
        "Gym & Fitness": 0
    },
    "Indie/Artsy": {
        "Music & Gig Nights": 3,
        "Corporate / Office": 0,
        "College Casual": 2,
        "Travel / Outdoor": 2,
        "Party & Clubbing": 1,
        "Chill at Home": 1,
        "Beach Vacation": 2,
        "Staycation / Getaway Weekends": 0,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 1,
        "Cafe Hopping / Bookstore Runs": 2,
        "Gym & Fitness": 0
    },
    "Y2K Revival": {
        "Music & Gig Nights": 3,
        "Corporate / Office": 0,
        "College Casual": 2,
        "Travel / Outdoor": 1,
        "Party & Clubbing": 3,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 0,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 2,
        "Cafe Hopping / Bookstore Runs": 1,
        "Gym & Fitness": 0
    },
    "Desi Modern": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 2,
        "College Casual": 1,
        "Travel / Outdoor": 1,
        "Party & Clubbing": 1,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 1,
        "Desi Parties / Get-Togethers": 3,
        "Date Nights": 2,
        "Cafe Hopping / Bookstore Runs": 2,
        "Gym & Fitness": 0
    },
    "Corporate Chic": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 3,
        "College Casual": 0,
        "Travel / Outdoor": 1,
        "Party & Clubbing": 0,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 1,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 2,
        "Cafe Hopping / Bookstore Runs": 1,
        "Gym & Fitness": 0
    },
    "Quiet Luxury": {
        "Music & Gig Nights": 0,
        "Corporate / Office": 3,
        "College Casual": 1,
        "Travel / Outdoor": 2,
        "Party & Clubbing": 0,
        "Chill at Home": 0,
        "Beach Vacation": 0,
        "Staycation / Getaway Weekends": 1,
        "Desi Parties / Get-Togethers": 0,
        "Date Nights": 2,
        "Cafe Hopping / Bookstore Runs": 1,
        "Gym & Fitness": 0
    }
}

In [23]:
techwearVectorLS = list(LifeStyleMapping["Techwear"].values())
AthleisureVectorLS = list(LifeStyleMapping["Athleisure"].values())
Old_MoneyvectorLS = list(LifeStyleMapping["Old Money"].values())
Skater_HHVectorLS = list(LifeStyleMapping["Skater Hip-Hop"].values())
Casual_CorpoVectorLS = list(LifeStyleMapping["Casual Corpo"].values())
Soft_GirlVectorLS = list(LifeStyleMapping["Soft Girl"].values())
Indie_ArtsyVectorLS = list(LifeStyleMapping["Indie/Artsy"].values())
Y2K_RevivalVectorLS = list(LifeStyleMapping["Y2K Revival"].values())
Desi_ModernVectorLS = list(LifeStyleMapping["Desi Modern"].values())
Corporate_ChicVectorLS = list(LifeStyleMapping["Corporate Chic"].values())
Quiet_LuxuryVectorLS = list(LifeStyleMapping["Quiet Luxury"].values())

In [26]:
lsMatrix = np.array([techwearVectorLS, AthleisureVectorLS, Old_MoneyvectorLS,
                     Skater_HHVectorLS, Casual_CorpoVectorLS, Soft_GirlVectorLS,
                     Indie_ArtsyVectorLS, Y2K_RevivalVectorLS, Desi_ModernVectorLS,
                     Corporate_ChicVectorLS, Quiet_LuxuryVectorLS])



In [25]:
print(lsMatrix)
print(lsMatrix.shape)

[[0 0 0 2 0 0 0 0 0 0 0 3]
 [0 0 1 2 0 2 0 0 0 0 0 3]
 [0 3 0 0 0 0 0 1 0 2 0 0]
 [2 0 2 0 2 0 0 0 0 0 0 0]
 [0 3 1 0 0 0 0 0 0 0 1 0]
 [0 0 2 1 0 1 0 0 0 2 3 0]
 [3 0 2 2 1 1 2 0 0 1 2 0]
 [3 0 2 1 3 0 0 0 0 2 1 0]
 [0 2 1 1 1 0 0 1 3 2 2 0]
 [0 3 0 1 0 0 0 1 0 2 1 0]
 [0 3 1 2 0 0 0 1 0 2 1 0]]
(11, 12)


In [16]:
lifestyleVector = [
    "Music & Gig Nights",
    "Corporate / Office",
    "College Casual",
    "Travel / Outdoor",
    "Party & Clubbing",
    "Chill at Home",
    "Beach Vacation",
    "Staycation / Getaway Weekends",
    "Desi Parties / Get-Togethers",
    "Date Nights",
    "Cafe Hopping / Bookstore Runs",
    "Gym & Fitness"
]

In [27]:
lifestylescore = {}

for clust,lifestyle in LifeStyleMapping.items():
  score = sum(lifestyle.values())
  lifestylescore[clust] = score

print(lifestylescore)

{
        "tags":[],
        "colors":[],
        "fabrics":[],
        "fits":[],
        "LifeStyleTags":[]
    }

{'Techwear': 5, 'Athleisure': 8, 'Old Money': 6, 'Skater Hip-Hop': 6, 'Casual Corpo': 5, 'Soft Girl': 9, 'Indie/Artsy': 14, 'Y2K Revival': 12, 'Desi Modern': 13, 'Corporate Chic': 8, 'Quiet Luxury': 10}


{'tags': [], 'colors': [], 'fabrics': [], 'fits': [], 'LifeStyleTags': []}

In [18]:
moodboardMap = {
    "oldMoney_QuietLux": {
        "tags": ["Classic","Polished","Timeless Elegance","Quiet Luxury"],
        "colors" : ["Monochrome-Neutrals","Earth-tones","Metallics"],
        "fabrics" : ["Wool","Cashmere", "Crisp" "Cotton", "Linen"],
        "fits" : ["Structured tailoring", "Straight fits", "Light layering "],
        "LifeStyleTags" :["Corporate","Staycation","Date Nights","Cafe Hopping"]
    },
    "CasualCorpo_CorporateChic": {
        "tags":["Minimalist","Classic","Corporate Chic","Polished"],
        "colors": ["Monochrome-Neutrals","Earth-tones"],
        "fabrics":["Linen", "Cotton"," Knitwear", "Leather accessories"],
        "fits":["Tailored shorts", "Structured blazers", "Relaxed straight trousers", "Button-ups"],
        "LifeStyleTags":["Corporate","Staycation","Date Nights","Cafe Hopping"]

    },
    "Desi_Modern" : {
        "tags":["Classic","Polished","Corporate Chic"],
        "colors":["Metallics","Monochrome-Neutrals","Earth-tones"],
        "fabrics":["Cotton", "Linen", "Light Silk blends"],
        "fits":["Structured kurta shirts"," tailored trousers", "fusion blazers"],
        "LifeStyleTags":["Corporate","Staycation","Date Nights","Cafe Hopping"]
    },
    "Techwear_luxe":{
        "tags":["Minimalist","Polished","Functional"],
        "colors":["Metallics","Monochrome-Neutrals"],
        "fabrics":[ "Nylon", "Water-resistant Cotton"," Knit layering"],
        "fits":["Structured outerwear" ," Straight trousers", "Monochrome layering"],
        "LifeStyleTags":["Corporate","Staycation","Date Nights","Cafe Hopping"]
    },
    "Athleisure_Minimalist":{
        "tags":["Minimalist","Sporty","Corporate Chic"],
        "colors":["Monochrome-Neutrals"],
        "fabrics":["Cotton", "Technical stretch", "Knitwear"],
        "fits":[ "Tailored joggers", "Straight knits", "Layered blazers" ," active tops"],
        "LifeStyleTags":["Corporate","Staycation","Date Nights","Cafe Hopping"]
    },
    "SoftGirl_NeutralLuxe": {
        "tags": ["Minimalist", "Romantic", "Polished"],
        "colors": ["Soft-Neutrals: , Light Taupe", "Earth-tones"],
        "fabrics": ["Knitwear", "Cotton", "Wool"],
        "fits": ["Soft Tailoring", "Straight Dresses", "Relaxed Knits"],
        "LifeStyleTags": ["Corporate/Office", "Café Hopping", "Staycation", "Date Nights"]
    },
    "IndieArtsy_PolishedNeutral": {
        "tags": ["Polished", "Classic", "Eclectic", "Functional", "Minimalist"],
        "colors": ["Neutrals", "Earth-tones"],
        "fabrics": ["Cotton", "Linen", "Wool", "Artisanal Textures"],
        "fits": ["Straight Trousers", "Layered Shirts", "Tailored Jackets", "Arty Accessories"],
        "LifeStyleTags": ["Corporate/Office", "Café Hopping", "Staycation", "Date Nights"]
    },
    "CorporateChic_QuietLuxury": {
        "tags": ["Classic", "Polished", "Luxury Minimalism", "Corporate Chic"],
        "colors": ["Monochrome-Neutrals", "Earth-tones"],
        "fabrics": ["Wool", "Cashmere", "Leather", "Silk"],
        "fits": ["Structured Blazers", "Tailored Trousers", "Silk Layering"],
        "LifeStyleTags": ["Corporate/Office", "Café Hopping", "Staycation", "Date Nights"]
    },
    "Cottagecore_Artsie": {
        "tags": ["Romantic", "Vintage Inspired", "Craft Aesthetic", "Artistic", "Handmade"],
        "colors": ["Soft Neutrals: Cream, Ivory, Beige", "Muted Pastels: Sage, Dusty Rose, Lavender", "Earth Tones: Olive, Warm Brown, Rust"],
        "fabrics": ["Cotton", "Linen", "Lace", "Crochet", "Embroidery"],
        "fits": ["Flowing Dresses", "Puff Sleeves", "Relaxed Skirts", "Aprons", "Layering Pieces"],
        "LifeStyleTags": ["Café Hopping/Bookstore Runs", "Staycation/Getaway Weekends", "Date Nights", "Home/Art Sessions"]
    },
    "Maximalist_Experimental": {
        "tags": ["Maximalist", "Bold Statements", "Eclectic", "Experimental", "Street Style"],
        "colors": ["Bold Brights: Red, Cobalt, Electric Green, Fuchsia", "Jewel Tones: Emerald, Sapphire, Ruby", "Patterns: Mixed Prints, Checkerboard, Stripes"],
        "fabrics": ["Satin", "Sequins", "Faux Fur", "Metallics", "Mixed Textures"],
        "fits": ["Oversized Layers", "Exaggerated Silhouettes", "Bold Tailoring", "Pattern Mixing"],
        "LifeStyleTags": ["Corporate/Office (Creative Fields)", "Café Hopping/Street Style", "Staycation/Creative Getaway", "Date Nights"]
    },
    "HyperFeminine_Barbiecore": {
        "tags": ["Hyper Feminine", "Y2K Revival", "Glam Polished", "Playful Chic"],
        "colors": ["Pastels: Baby Pink, Lavender, Mint", "Bold Brights: Hot Pink, Magenta", "Metallic Accents: Sparkle Silver, Glossy Gold"],
        "fabrics": ["Satin", "Silk", "Sequins", "Knitwear ", "Faux Fur"],
        "fits": ["Mini Dresses", "Bodycon", "Cropped Tops", "Pleated Skirts", "Playful Tailoring"],
        "LifeStyleTags": ["Corporate/Office ", "Café Hopping/Bookstore Runs", "Staycation/Getaway", "Date Nights"]
    }
}


## 44-dimensional cluster matrix

In [ ]:
complete_matrix = np.concatenate([clusterMatrix, lsMatrix, colorMatrix], axis=1)
print(f"Complete matrix shape: {complete_matrix.shape}")  

Complete matrix shape: (11, 44)
